### ISSUE TITLE
Multi-threads supporting

### ISSUE THREAD

**Issue by esctrionsit** [ZhangZhaoheng24/kmer_scan#1]
Hi,

Will this pipline support multi-threads in future updates? That would helps a lot!

Thanks!

**Comment by ZhangZhaoheng24** [comment]
Hi,
Thank you for your interest in our pipeline! We appreciate your suggestion regarding the support for multi-threading. We are constantly working to improve our pipeline and will definitely consider adding multi-threading support in our future updates.
Best regards.
